// Class automatically generated by Dev-C++ New Class wizard

#ifndef BATERIA_H
#define BATERIA_H
#include <vector.h>
#include "Cuerpo.h"
#include <SDL/SDL_mixer.h>

// Aca voy a definir una vector de cuerpos en la que cada nodo va representara el numero de canal en donde sera reproducido
class Bateria
{
    private:
        vector<Cuerpo* > elemento;
        int canales;
	public:
		Bateria(int canales);
        void addCuerpo(Cuerpo *c);
        void reproducirCuerpo(int num);
		~Bateria();
};

#endif // BATERIA_H
