// Class automatically generated by Dev-C++ New Class wizard

#include "Bateria.h" // class's header file

// class constructor
Bateria::Bateria(int canales)
{
    this->canales = canales;
    Mix_AllocateChannels(canales);
    Mix_ReserveChannels(canales);
    for (int i = 0; i<canales;i++)
         Mix_GroupChannels(i, i+1, i);

}

void Bateria::addCuerpo(Cuerpo *c)
{
      this->elemento.push_back(c);
}
void Bateria::reproducirCuerpo(int num)
{
    elemento[num]->Reproducir();
}
Bateria::~Bateria()
{
	atexit(Mix_CloseAudio);
}
