// Class automatically generated by Dev-C++ New Class wizard

#ifndef CUERPO_H
#define CUERPO_H
#include <SDL/SDL_mixer.h>
// En esta clase se guadaran la direccion, el nombre y la duracion del sonido

class Cuerpo
{
    private:
        Mix_Chunk* sonido;
        char* nombre;
        int volumen;
        int canal;
	public:
		// class constructor
		Cuerpo(char *nombre, char * sonido, int volumen, int canal);
        void setVolumen(int volumen);
        int getVolumen();
        void Reproducir();
		~Cuerpo();
};

#endif // CUERPO_H
